In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('넘파이 배열에 저장된 데이터\n', arr)

넘파이 배열 파일 입출력

In [2]:
# numpy는 배열 객체를 바이너리 파일 또는 텍스트 파일에 저장하고 로딩하는 기능을 제공한다.
# 메소드 이름    기능                                               파일포맷
# np.save()      numpy 배열 객체 1개를 파일에 저장한다.             바이너리
# np.savez()     numpy 배열 객체 여러개를 파일에 저장한다.          바이너리
# np.load()      numpy 배열 저장 파일로 부터 객체를 읽어온다.       바이너리
# np.savetxt()   numpy 배열 객체를 텍스트 파일에 저장한다.          텍스트 => txt(X), csv, tsv(O)
# np.loadtxt()   텍스트 파일에 저장된 numpy 배열 객체를 읽어온다.   텍스트

In [4]:
np.random.seed(100)
a = np.random.randint(1, 10, (2, 3))
pprint(a)
b = np.random.randint(1, 10, (2, 3))
pprint(b)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
넘파이 배열에 저장된 데이터
 [[9 9 4]
 [8 8 1]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
넘파이 배열에 저장된 데이터
 [[5 3 6]
 [3 3 3]]


In [6]:
# 배열 객체 저장 - 바이너리 파일
# save(), savez() 함수를 이용해서 배열 객체를 바이너리(2진) 형태의 파일로 저장할 수 있다.
# save('파일이름', 배열이름): 배열 1개를 저장한다. 확장명 => npy
# savez('파일이름', 배열이름1, 배열이름2, ...): 배열 여러개를 저장한다. 확장명 => npz

# a 배열을 파일로 저장한다.
np.save('./output/my_array1', a)